apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Prometheus
# helm template --namespace default prometheus prometheus-community/prometheus -f values.yaml > prometheus.yaml

resources:
  - prometheus.yaml

patchesStrategicMerge:
  - configmap-alerting.yaml

namespace: prometheus

commonLabels:
  app: prometheus